# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4fdedd90d6ba2cbec9c01dd8cfafe2d9eefd7cbc64e30dad5d02ee321e4681b0f7acbe3f77460014b08c735d3f23f4e64ea54c24402be990a9f0c3675eac9aba

test:
  secret_key_base: e4b168b7f6c54412ec39d45178e211e60af5f95bb78e3ce494d78491d8b603038324ff5e3502f63262549fa719f72768c22fe5d301de6859560069b098f77e73

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
